#!/bin/bash

source $(dirname $0)/lib/common.sh

print_usage() {
  echo "Usage: $executable_name [<game-directory>]"
  echo
  echo "This script builds and installs the game on a connected Android device."
  echo
  echo "Arguments:"
  echo "  <game-directory>  The directory of the game to build and install. Defaults to 'mygame' if not specified."
  echo
  echo "Notes:"
  echo "  - The script requires the 'android' directory to be present. Please run 'setup-basic-environment' first."
  echo "  - The ANDROID_SERIAL environment variable can be used to specify the device if there are multiple devices connected."
  echo
  echo "Run '$executable_name --help' to display this message."
}

if [ "$1" == "--help" ]; then
  print_usage
  exit
fi

game_directory=${1:-mygame}

DEV_KEYSTORE_PATH=./android/dev_keystore.jks
DEV_KEYSTORE_PASSWORD=mygame

if [ ! -f $DEV_KEYSTORE_PATH ]; then
  log "Generating dev keystore at $DEV_KEYSTORE_PATH"
  $tools_dir/generate-keystore $DEV_KEYSTORE_PATH \
                               -alias mygame \
                               -storepass $DEV_KEYSTORE_PASSWORD \
                               -dname "CN=mygame, OU=mygame, O=mygame, L=mygame, S=mygame, C=us"
  echo $DEV_KEYSTORE_PASSWORD > $DEV_KEYSTORE_PATH.pass
fi

$tools_dir/build-signed-apk $DEV_KEYSTORE_PATH $game_directory

gameid=$(get_metadata $game_directory gameid)
packageid=$(get_metadata $game_directory packageid)

log "Installing the APK on the device and restarting the app"
adb shell am force-stop $packageid
adb uninstall $packageid || true # In case the app was never installed
adb install ./builds/$gameid-signed.apk
adb shell am start -n $packageid/$packageid.DragonRubyActivity

$tools_dir/tail-game-logs $game_directory
