#!/bin/bash

source $(dirname $0)/lib/common.sh

print_usage() {
  echo "Usage: $executable_name [<game-directory>]"
  echo
  echo "Builds and installs the game on a connected Android device."
  echo
  echo "If <game-directory> is not specified, 'mygame' is used."
  echo "Use the ANDROID_SERIAL environment variable to specify the device if there are multiple devices connected."
}

if [ "$1" == "--help" ]; then
  print_usage
  exit
fi

game_directory=${1:-mygame}

DEV_KEYSTORE_PATH=./android/dev_keystore.jks
DEV_KEYSTORE_PASSWORD=mygame

if [ ! -f $DEV_KEYSTORE_PATH ]; then
  log "Generating dev keystore at $DEV_KEYSTORE_PATH"
  $tools_dir/generate-keystore $DEV_KEYSTORE_PATH \
                               -alias mygame \
                               -storepass $DEV_KEYSTORE_PASSWORD \
                               -dname "CN=mygame, OU=mygame, O=mygame, L=mygame, S=mygame, C=us"
fi

gameid=$(get_metadata $game_directory gameid)
packageid=$(get_metadata $game_directory packageid)

./dragonruby-publish --package --platforms=googleplay $game_directory

log "Extracting the APKs from the AAB file"
java -jar ./android/bundletool.jar build-apks \
     --bundle=./builds/$gameid-googleplay.aab \
     --output=./builds/app.apks \
     --mode=universal

mv ./builds/app.apks ./builds/app.zip
rm -rf ./builds/tmp
mkdir ./builds/tmp
unzip ./builds/app.zip -d ./builds/tmp

log "Signing the APK"
apksigner sign \
          --ks $DEV_KEYSTORE_PATH \
          --ks-pass pass:$DEV_KEYSTORE_PASSWORD \
          ./builds/tmp/universal.apk

log "Installing the APK on the device and restarting the app"
adb shell am force-stop $packageid
adb uninstall $packageid || true # In case the app was never installed
adb install ./builds/tmp/universal.apk
adb shell am start -n $packageid/$packageid.DragonRubyActivity

$tools_dir/tail-game-logs $game_directory
