#!/bin/bash

source $(dirname $0)/lib/common.sh

print_usage() {
  echo "Usage: $executable_name <path-to-extension> [<game-directory>]"
  echo
  echo "This script builds the C extension at <path-to-extension> and installs it in the specified game directory."
  echo
  echo "Arguments:"
  echo "  <path-to-extension>  The path to the C extension source file."
  echo "  <game-directory>     The directory of the game to install the extension. Defaults to 'mygame' if not specified."
  echo
  echo "Notes:"
  echo "  - The script requires the 'android' directory to be present. Please run 'setup-basic-environment' first."
  echo "  - The script requires the Android NDK to be installed. Please run 'setup-cext-environment' first."
  echo
  echo "Run '$executable_name --help' to display this message."
}

if [[ $1 == "--help" ]]; then
  print_usage
  exit
fi

path_to_extension=$1
game_directory=${2:-mygame}

if [ -z $path_to_extension ]; then
  echo "Error: <path-to-extension> is required" >&2
  echo >&2
  print_usage
  exit 1
fi

clang() {
  if [ $(uname) = "Darwin" ]; then
    ndk_platform="darwin-x86_64"
  elif [ $(uname) = "Linux" ]; then
    ndk_platform="linux-x86_64"
  else
    echo "Unsupported platform: $(uname)" >&2
    exit 1
  fi

  ndk_llvm_path="./android/ndk/$NDK_VERSION/toolchains/llvm/prebuilt/$ndk_platform"
  $ndk_llvm_path/bin/clang --sysroot=$ndk_llvm_path/sysroot $@
}

extension_name=$(basename -s .c $path_to_extension)

TARGETS=(
  "arm64,aarch64-linux-android33"
  "arm32,armv7a-linux-androideabi33"
)

for target in "${TARGETS[@]}"; do
  IFS=',' read -r dr_target clang_target <<< "$target"

  output_path="./$game_directory/native/googleplay-$dr_target"
  mkdir -p $output_path

  log "Compiling '$path_to_extension' to '$output_path/$extension_name.so'"

  clang -shared \
        -target $clang_target \
        -Wl,-undefined -Wl,dynamic_lookup \
        -fPIC \
        -I ./include \
        $path_to_extension \
        -o $output_path/$extension_name.so
done
