#!/bin/bash

source $(dirname $0)/lib/common.sh

print_usage() {
  echo "Usage: $executable_name <keystore_path> [keytool options]"
  echo
  echo "Generates a new key store for signing Android apps."
}

if [ "$1" == "--help" ]; then
  print_usage
  exit 0
fi

keystore_path=$1
shift

if [ -z "$keystore_path" ]; then
  echo "Error: keystore path is required."
  print_usage
  exit 1
fi

keytool -genkeypair -v \
        -keystore $keystore_path \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        "$@"
