#!/bin/bash

source $(dirname $0)/lib/common.sh

print_usage() {
  echo "Usage: $executable_name <keystore_path> [keytool options]"
  echo
  echo "Generates a new key store for signing Android apps."
  echo
  echo "Arguments:"
  echo "  <keystore_path>    The path where the keystore will be created."
  echo "  [keytool options]  Additional options to pass to the keytool command."
  echo
  echo "Examples:"
  echo "  $executable_name my-release-key.keystore"
  echo "  $executable_name my-release-key.keystore -alias mykey -keypass mypass"
}

if [ "$1" == "--help" ]; then
  print_usage
  exit 0
fi

keystore_path=$1
shift

if [ -z "$keystore_path" ]; then
  echo "Error: keystore path is required."
  print_usage
  exit 1
fi

keytool -genkeypair -v \
        -keystore $keystore_path \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        "$@"
