#!/bin/sh

source $(dirname $0)/lib/common.sh
source $(dirname $0)/lib/tool_versions.sh

if [ ! -d android ]; then
  log "android directory not found, please execute setup-basic-environment first"
  exit 1
fi

if [ -d android/platforms ]; then
  log "Android SDK already installed, skipping"
else
  log "Installing Android SDK $ANDROID_SDK_VERSION"
  sdkmanager --install "platforms;android-$ANDROID_SDK_VERSION"
fi

if [ -d android/ndk ]; then
  log "Android NDK already installed, skipping"
else
  log "Installing Android NDK $NDK_VERSION"
  sdkmanager --install "ndk;$NDK_VERSION"
fi
