#!/bin/sh

# Defines executable_name, sdkmanager and log
source $(dirname $0)/lib/common.sh

ANDROID_SDK_VERSION=34
NDK_VERSION=26.3.11579264

if [ ! -d android ]; then
  log "android directory not found, please execute setup-basic-environment first"
  exit 1
fi

if [ -d android/platforms ]; then
  log "Android SDK already installed, skipping"
else
  log "Installing Android SDK $ANDROID_SDK_VERSION"
  sdkmanager --install "platforms;android-$ANDROID_SDK_VERSION"
fi

if [ -d android/ndk ]; then
  log "Android NDK already installed, skipping"
else
  log "Installing Android NDK $NDK_VERSION"
  sdkmanager --install "ndk;$NDK_VERSION"
fi
